import puppeteer from 'puppeteer-core'
const browser = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null, protocolTimeout: 240000 })
const page = (await browser.pages()).find(p => p.url().includes('craftflow-git-dev'))
const sleep = ms => new Promise(r => setTimeout(r, ms))
const text = () => page.evaluate(() => document.body.innerText)
const r = await page.evaluate(() => { const b = [...document.querySelectorAll('button')].find(b => b.innerText.trim() === 'Abbrechen'); if (!b) return false; b.click(); return true })
console.log('Abbrechen geklickt:', r); await sleep(1500)
let t = await text()
console.log('Dialog noch offen:', t.includes('ANGEBOT LÖSCHEN'), '| Jana Meitner vorhanden:', t.includes('Jana Meitner'), '| Projekte sichtbar:', (t.match(/Öffnen →/g) || []).length)
browser.disconnect()
