import puppeteer from 'puppeteer-core'
const b = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null })
const app = (await b.pages()).find(p => p.url().includes('vercel.app'))
await app.bringToFront()
await app.evaluate(() => { const k = [...document.querySelectorAll('button')].find(e => /Angebot/.test(e.textContent) && e.textContent.length < 20); if (k) k.click() })
await new Promise(r => setTimeout(r, 1800))
await app.evaluate(() => window.scrollTo(0, 0))
await new Promise(r => setTimeout(r, 400))
await app.screenshot({ path: '.tmp-cu/a-ganz.png' })
const t = await app.evaluate(() => document.body.innerText.replace(/\s+/g, ' ').slice(0, 800))
console.log(t)
await b.disconnect()
