import puppeteer from 'puppeteer-core'
const b = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null })
const app = (await b.pages()).find(p => p.url().includes('vercel.app'))
await app.bringToFront()
await app.screenshot({ path: '.tmp-cu/verlassen.png', clip: { x: 488, y: 412, width: 426, height: 172 }, captureBeyondViewport: false })
console.log('Dialog aufgenommen')
await app.evaluate(() => { const k = [...document.querySelectorAll('button')].find(e => /Speichern und weiter/.test(e.textContent)); if (k) k.click() })
await new Promise(r => setTimeout(r, 3000))
const t = await app.evaluate(() => document.body.innerText.replace(/\s+/g, ' ').slice(0, 500))
console.log(t)
await b.disconnect()
