import puppeteer from 'puppeteer-core'
const browser = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null })
const sleep = ms => new Promise(r => setTimeout(r, ms))
const page = await browser.newPage(); await page.setViewport({ width: 1280, height: 1000 })
await page.goto('https://craftflow-git-dev-fabian-scharf-s-projects.vercel.app/settings?nc=' + Date.now(), { waitUntil: 'domcontentloaded', timeout: 90000 }); await sleep(5000)
await page.evaluate(() => { const el = [...document.querySelectorAll('button, div, span, a')].find(e => e.children.length <= 2 && e.innerText && e.innerText.trim() === 'E-Mail & Versand'); el && el.click() }); await sleep(3500)
const t = await page.evaluate(() => document.body.innerText)
console.log(JSON.stringify({ starterSperre: t.includes('ist ab dem Starter-Plan'), smtpSperre: t.includes('SMTP-Konfiguration ist ab dem'), smtpFelder: /SMTP-Server|SMTP-Host|Host|Port/.test(t), signatur: t.includes('E-MAIL-SIGNATUR') }))
await page.screenshot({ path: '/tmp/cfshots/email-bereich.png' })
await page.close(); browser.disconnect()
