import puppeteer from 'puppeteer-core'
const browser = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null })
const sleep = ms => new Promise(r => setTimeout(r, ms))
const page = await browser.newPage()
await page.bringToFront()
await page.goto('https://craftflow-git-dev-fabian-scharf-s-projects.vercel.app/settings', { waitUntil: 'networkidle2', timeout: 90000 }); await sleep(2500)
await page.evaluate(() => { const el = [...document.querySelectorAll('button, div, span, a')].find(e => e.children.length <= 2 && e.innerText && e.innerText.trim() === 'Marketing & CI'); el && el.click() }); await sleep(1000)
const lies = () => page.evaluate(() => ({ wert: document.querySelectorAll('input[maxlength="7"]')[1].value, aktiv: document.activeElement?.tagName + '/' + (document.activeElement?.getAttribute('maxlength') || document.activeElement?.type || ''), picker: document.querySelectorAll('input[type="color"]')[1].value }))
const feld = (await page.$$('input[maxlength="7"]'))[1]
await feld.focus(); await page.evaluate(el => el.select(), feld); await sleep(100)
console.log('nach Fokus+select:', JSON.stringify(await lies()))
await page.keyboard.type('c8102e', { delay: 30 }); await sleep(300)
console.log('nach Tippen:', JSON.stringify(await lies()))
await page.keyboard.press('Tab'); await sleep(300)
console.log('nach Tab:', JSON.stringify(await lies()))
await page.screenshot({ path: '/tmp/cfshots/dev-blur.png', clip: { x: 380, y: 160, width: 700, height: 240 } })
await page.close(); browser.disconnect()
