import puppeteer from 'puppeteer-core'
const b = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null })
const t = (await b.pages()).find(p => p.url().includes('craftflow-git-dev')) || await b.newPage()
await t.bringToFront()
await t.setViewport({ width: 1400, height: 1100, deviceScaleFactor: 2 })
await t.goto('https://craftflow-git-dev-fabian-scharf-s-projects.vercel.app/settings', { waitUntil: 'networkidle2', timeout: 90000 })
await new Promise(r => setTimeout(r, 3000))
await t.evaluate(() => { const k = [...document.querySelectorAll('button, a, div')].filter(e => e.textContent.trim().endsWith('Wünsche') && e.textContent.trim().length < 20 && e.getBoundingClientRect().x < 300); if (k.length) k[k.length-1].click() })
await new Promise(r => setTimeout(r, 3000))
const d = await t.evaluate(() => { const h = document.body.innerText.replace(/\s+/g,' '); const i = h.indexOf('Abmelden'); return h.slice(i+9, i+1000) })
console.log(d)
await t.screenshot({ path: '.tmp-cu/wuensche.png', captureBeyondViewport: false })
await b.disconnect()
