import puppeteer from 'puppeteer-core'
const b = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null })
const app = (await b.pages()).find(p => p.url().includes('vercel.app'))
await app.bringToFront()
const knoepfe = await app.evaluate(() => [...document.querySelectorAll('button')].map((e,i) => `${i}:"${e.textContent.trim().slice(0,18)}"`).slice(0,10))
console.log(knoepfe.join(' '))
await app.evaluate(() => { const k = [...document.querySelectorAll('button')].filter(e => /📋/.test(e.textContent)); if (k.length) k[0].click() })
await new Promise(r => setTimeout(r, 2500))
const t = await app.evaluate(() => document.body.innerText.replace(/\s+/g, ' ').slice(0, 900))
console.log('\nINHALT:', t)
await b.disconnect()
