import puppeteer from 'puppeteer-core'
const b = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null })
const t = await b.newPage()
await t.setViewport({ width: 1440, height: 1100, deviceScaleFactor: 1 })
await t.goto('http://localhost:4322/werkstatt', { waitUntil: 'networkidle2', timeout: 60000 })
await new Promise(r => setTimeout(r, 1200))
const y = await t.evaluate(() => { const g = document.querySelector('[class*="gross"]'); window.scrollTo(0, g.getBoundingClientRect().top + window.pageYOffset - 24); return Math.round(window.pageYOffset) })
await new Promise(r => setTimeout(r, 900))
await t.screenshot({ path: '.tmp-cu/raster.png', captureBeyondViewport: false })
console.log('gescrollt auf', y)
await b.disconnect()
