import puppeteer from 'puppeteer-core'
const sleep = ms => new Promise(r => setTimeout(r, ms))
const browser = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null })
const page = await browser.newPage(); await page.setViewport({ width: 1280, height: 1000 })
await page.goto('https://craftflow-git-dev-fabian-scharf-s-projects.vercel.app/settings', { waitUntil: 'networkidle2', timeout: 90000 }); await sleep(3000)
const nav = await page.evaluate(() => [...document.querySelectorAll('.nav-item, nav a, nav button, aside *')].map(e => e.innerText?.trim()).filter(Boolean).slice(0, 30))
console.log('NAV', JSON.stringify(nav))
const ok = await page.evaluate(() => { const els = [...document.querySelectorAll('*')].filter(e => e.childElementCount === 0 && e.innerText?.trim() === 'Mein Betrieb'); if (!els.length) return 0; (els[0].closest('button, a, .nav-item') || els[0]).click(); return els.length })
console.log('klick', ok); await sleep(4000)
const btns = await page.evaluate(() => [...document.querySelectorAll('button')].map(b => b.innerText.trim()).filter(Boolean).slice(0, 40))
console.log('BUTTONS', JSON.stringify(btns))
console.log('H2', await page.evaluate(() => [...document.querySelectorAll('h2')].map(h => h.innerText)))
await page.screenshot({ path: '.tmp-cu/referenz-debug.png' })
await page.close(); browser.disconnect()
