import puppeteer from 'puppeteer-core'
const sleep = ms => new Promise(r => setTimeout(r, ms))
const browser = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null })
const page = await browser.newPage(); await page.setViewport({ width: 1280, height: 1000 })
await page.goto('https://craftflow-git-dev-fabian-scharf-s-projects.vercel.app/settings', { waitUntil: 'networkidle2', timeout: 90000 }); await sleep(3000)
const api = await page.evaluate(async () => (await (await fetch('/api/settings/kalibrierung?schwerpunkt=einbau,bad,treppen&maschinen=cnc,kantenanleim&montage_selbst=immer', { cache: 'no-store' })).json()).referenzprojekt?.name)
console.log('API einbau,bad,treppen →', api)
await page.evaluate(() => { const els = [...document.querySelectorAll('*')].filter(e => e.childElementCount === 0 && e.innerText?.trim() === 'Mein Betrieb'); if (els.length) (els[0].closest('button, a, .nav-item') || els[0]).click() }); await sleep(4000)
const kopf = () => page.evaluate(() => (document.body.innerText.match(/Das Referenzprojekt: [^\n]+/) || [''])[0])
const klick = txt => page.evaluate(t => { const b = [...document.querySelectorAll('button')].find(b => b.innerText.trim().startsWith(t)); if (b) b.click(); return b ? b.innerText.split('\n')[0] : null }, txt)
console.log(await klick('Küchen'), '→'); await sleep(5000); console.log(await kopf())
console.log(await klick('Treppen'), '→'); await sleep(6000); console.log(await kopf())
console.log(await klick('Treppen'), await klick('Küchen'), '→'); await sleep(5000); console.log(await kopf())
await page.close(); browser.disconnect()
