import puppeteer from 'puppeteer-core'
const b = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null })
const app = (await b.pages()).find(p => p.url().includes('vercel.app'))
await app.bringToFront()
await app.evaluate(() => { const k = [...document.querySelectorAll('button')].find(e => /Regel selbst anlegen/.test(e.textContent)); if (k) k.click() })
await new Promise(r => setTimeout(r, 1200))
const t = await app.evaluate(() => { const h = document.body.innerText.replace(/\s+/g, ' '); const i = h.indexOf('Abmelden'); return h.slice(i + 9, i + 900) })
console.log(t)
await app.screenshot({ path: '.tmp-cu/bauweise.png', captureBeyondViewport: false })
await b.disconnect()
