import puppeteer from 'puppeteer-core'
const browser = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null, protocolTimeout: 60000 })
const page = (await browser.pages()).find(p => p.url().includes('resend.com'))
const sleep = ms => new Promise(r => setTimeout(r, ms))
const text = () => page.evaluate(() => document.body.innerText)
await page.reload({ waitUntil: 'networkidle2' }); await sleep(4000)
let t = await text(); let i = t.indexOf('DNS Records'); console.log('--- SEITE fscrafted.de ---\n' + t.slice(i, i + 1800))
const rows = await page.evaluate(() => [...document.querySelectorAll('table tr')].map(tr => [...tr.querySelectorAll('th,td')].map(td => { const c = td.querySelector('[aria-label^="Copy "]'); return c ? c.getAttribute('aria-label').slice(5) : td.innerText.trim().replace(/\n/g, ' ') }).join(' | ')))
console.log('--- TABELLEN ---\n' + rows.join('\n'))
// Domainliste
await page.goto('https://resend.com/domains', { waitUntil: 'networkidle2' }); await sleep(4000)
t = await text(); i = t.indexOf('Domains', t.indexOf('Need help?')); console.log('--- LISTE ---\n' + t.slice(i, i + 600))
const links = await page.evaluate(() => [...document.querySelectorAll('a')].map(a => ({ h: a.href, t: a.innerText.trim().slice(0, 40) })).filter(x => /\/domains\/[0-9a-f-]{36}/.test(x.h)))
console.log('Domain-Links:', JSON.stringify(links))
browser.disconnect()
