import puppeteer from 'puppeteer-core'
const browser = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null, protocolTimeout: 60000 })
const page = (await browser.pages()).find(p => p.url().includes('resend.com'))
const sleep = ms => new Promise(r => setTimeout(r, ms))
const tracking = await page.evaluate(() => [...document.querySelectorAll('input[type=checkbox], [role=switch], [role=checkbox]')].map(e => (e.getAttribute('aria-checked') ?? e.checked) + ''))
console.log('Tracking-Schalter:', tracking)
await page.evaluate(() => { const b = [...document.querySelectorAll('button')].find(b => b.innerText.trim() === 'Add domain'); b && b.click() })
await sleep(6000)
console.log('URL:', page.url())
const t = await page.evaluate(() => document.body.innerText)
const i = t.indexOf('DNS'); console.log(t.slice(Math.max(0, i - 400), i + 2500))
await page.screenshot({ path: '/tmp/cfshots/resend-dns.png', fullPage: true })
browser.disconnect()
