import puppeteer from 'puppeteer-core'
const browser = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null, protocolTimeout: 60000 })
const page = (await browser.pages()).find(p => p.url().includes('resend.com'))
const sleep = ms => new Promise(r => setTimeout(r, ms))
const text = () => page.evaluate(() => document.body.innerText)
await page.goto('https://resend.com/domains/add', { waitUntil: 'networkidle2', timeout: 60000 }); await sleep(4000)
const st = await page.evaluate(() => { const inp = document.querySelector('input[placeholder="updates.example.com"]'); if (!inp) return 'kein Feld'; const d = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value'); d.set.call(inp, 'fscrafted.de'); inp.dispatchEvent(new Event('input', { bubbles: true })); inp.dispatchEvent(new Event('change', { bubbles: true })); return 'Feld: ' + inp.value })
console.log(st); await sleep(800)
const btn = await page.evaluate(() => { const b = [...document.querySelectorAll('button')].find(b => b.innerText.trim() === 'Add domain'); return b ? { disabled: b.disabled, txt: b.innerText } : null })
console.log('Button:', JSON.stringify(btn))
await page.evaluate(() => { const b = [...document.querySelectorAll('button')].find(b => b.innerText.trim() === 'Add domain'); b && b.click() })
for (let i = 0; i < 10; i++) { await sleep(1500); if (page.url().includes('/domains/add/')) break }
console.log('URL:', page.url())
let t = await text(); const err = t.match(/(already|exists|invalid|error)[^\n]*/i); if (err) console.log('Hinweis:', err[0])
await page.evaluate(() => { const b = [...document.querySelectorAll('button, a')].find(b => b.innerText.trim() === 'Manual setup'); b && b.click() }); await sleep(3000)
const rows = await page.evaluate(() => [...document.querySelectorAll('table tr')].map(tr => [...tr.querySelectorAll('th,td')].map(td => { const c = td.querySelector('[aria-label^="Copy "]'); return c ? c.getAttribute('aria-label').slice(5) : td.innerText.trim().replace(/\n/g, ' ') }).join(' | ')))
console.log('--- DNS fscrafted.de ---\n' + rows.join('\n'))
await page.screenshot({ path: '/tmp/cfshots/resend-dns-fscrafted.png', fullPage: true })
browser.disconnect()
