import puppeteer from 'puppeteer-core'
const b = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null })
const t = (await b.pages()).find(p => p.url().includes('craftflow-git-dev'))
await t.bringToFront()
await t.goto('https://craftflow-git-dev-fabian-scharf-s-projects.vercel.app/', { waitUntil: 'networkidle2', timeout: 90000 })
await new Promise(r => setTimeout(r, 2500))
await t.evaluate(() => { const k = [...document.querySelectorAll('button')].find(e => e.textContent.trim() === '📋'); if (k) k.click() })
await new Promise(r => setTimeout(r, 2500))
await t.evaluate(() => { const k = [...document.querySelectorAll('button')].find(e => /Öffnen/.test(e.textContent)); if (k) k.click() })
await new Promise(r => setTimeout(r, 3500))
await t.evaluate(() => { const k = [...document.querySelectorAll('button')].find(e => /Kalkulation/.test(e.textContent) && e.textContent.length < 20); if (k) k.click() })
await new Promise(r => setTimeout(r, 2000))
const d = await t.evaluate(() => {
  const txt = document.body.innerText.replace(/\s+/g, ' ')
  const titel = [...document.querySelectorAll('input')].filter(e => e.type === 'text' && e.value && !/Gruppe/.test(e.placeholder || '')).map(e => e.value)
  const zahl = [...document.querySelectorAll('input')].filter(e => e.type === 'number').map(e => e.value)
  const m = txt.match(/POSITIONEN (\d+) NETTO ([\d.,]+ €).*?MATERIALKOSTEN GESAMT ([\d.,]+ €) STUNDEN GESAMT ([\d.,]+ h)/)
  return { kennzahlen: m ? m.slice(1) : 'nicht gefunden', titel: titel.slice(0, 4), stueck: zahl.slice(0, 2) }
})
console.log(JSON.stringify(d, null, 1))
await b.disconnect()
