import puppeteer from 'puppeteer-core'
const browser = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null, protocolTimeout: 120000 })
const page = await browser.newPage()
await page.setViewport({ width: 1366, height: 1000 })
await page.goto('https://supabase.com/dashboard/project/fepfjvixfxksvduzwsgq/auth/url-configuration', { waitUntil: 'networkidle2', timeout: 90000 })
await new Promise(r => setTimeout(r, 4000))
const t = await page.evaluate(() => document.body.innerText)
const i = t.indexOf('Site URL'); console.log(t.slice(Math.max(0, i - 100), i + 1800))
await page.screenshot({ path: '/tmp/cfshots/supa-url.png', fullPage: true })
console.log('URL:', page.url())
browser.disconnect()
