import puppeteer from 'puppeteer-core'
const b = await puppeteer.connect({ browserURL: 'http://localhost:9222', defaultViewport: null })
const t = (await b.pages()).find(p => p.url().includes('craftflow-git-dev'))
await t.bringToFront()
await t.setViewport({ width: 1400, height: 1000, deviceScaleFactor: 2 })
await t.goto('https://craftflow-git-dev-fabian-scharf-s-projects.vercel.app/', { waitUntil: 'networkidle2', timeout: 90000 })
await new Promise(r => setTimeout(r, 3000))
await t.evaluate(() => { const k = [...document.querySelectorAll('button')].find(e => e.textContent.trim() === '📋'); if (k) k.click() })
await new Promise(r => setTimeout(r, 2500))
await t.evaluate(() => { const k = [...document.querySelectorAll('button')].find(e => /Öffnen/.test(e.textContent)); if (k) k.click() })
await new Promise(r => setTimeout(r, 3500))
await t.evaluate(() => { const k = [...document.querySelectorAll('button')].find(e => /Angebot/.test(e.textContent) && e.textContent.length < 20); if (k) k.click() })
await new Promise(r => setTimeout(r, 2000))
await t.evaluate(() => { [...document.querySelectorAll('button, div')].filter(e => { const s = getComputedStyle(e); const r = e.getBoundingClientRect(); return s.position === 'fixed' && r.width < 120 && r.height < 120 && r.x > 1200 }).forEach(e => (e.dataset.weg='1', e.style.visibility='hidden')) })
const mass = async () => t.evaluate(() => {
  const l = [...document.querySelectorAll('*')].find(e => e.children.length === 0 && /Textbausteine in diesem Angebot/i.test(e.textContent || ''))
  const hinweis = [...document.querySelectorAll('*')].find(e => e.children.length === 0 && /Anlegen und ändern unter/.test(e.textContent || ''))
  const a = l.getBoundingClientRect(), z = hinweis.getBoundingClientRect()
  return { x: Math.round(a.x) - 16, y: Math.round(a.y) - 14, h: Math.round(z.bottom - a.y) + 28 }
})
let m = await mass()
await t.screenshot({ path: '.tmp-cu/tb-aus.png', clip: { x: m.x, y: m.y, width: 700, height: m.h }, captureBeyondViewport: false })
// anwaehlen
await t.evaluate(() => { const k = [...document.querySelectorAll('button')].find(e => /^\+\s/.test(e.textContent.trim())); if (k) k.click() })
await new Promise(r => setTimeout(r, 1200))
m = await mass()
await t.screenshot({ path: '.tmp-cu/tb-an.png', clip: { x: m.x, y: m.y, width: 700, height: m.h }, captureBeyondViewport: false })
const zustand = await t.evaluate(() => [...document.querySelectorAll('button')].filter(e => /35a/.test(e.textContent)).map(e => e.textContent.trim()))
console.log('Zustand nach Klick:', JSON.stringify(zustand))
await t.evaluate(() => document.querySelectorAll('[data-weg]').forEach(e => (e.style.visibility='', delete e.dataset.weg)))
await b.disconnect()
